/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h> 
#include <netinet/in.h>
#include <signal.h>

#include "LaCadena.h"
#include "Inventario.h"

#define BUFFER_SIZE 10000

/**
 * Funcion que carga el archivo de inventarios en el servidor y luego
 * dado la cadena de pedidos del cliente, la recorre y busca ese producto en 
 * su inventario, lo concatena junto con su precio y cantidad a un string que despues
 * va a ser pasado como respuesta. 
 * @param **argp string que contiene los pedidos del cliente. 
 * @return devuelve un string de la forma nombreProducto&cantidad&precio&nombreProducto...
 * que viene a ser la informacion de los productos con que cuenta el servidor de los
 * que necesita el cliente.
 */
char ** obtenerinventario_1_svc(char **argp, struct svc_req *rqstp) {

	/*
	if(inventarios == NULL) {
		create(&inventarios);
		cargarInventarios(INVENTARIO);
	}
	*/
	create(&inventarios);
	cargarInventarios(INVENTARIO);

	static char *result;
	char aux[BUFFER_SIZE];
	Inventario * inventario;
	char * pch;
	char * str;
	char convert [33];
	str = *argp;
	bzero(aux, BUFFER_SIZE);
	
	pch = strtok(str, "&");
	while (pch != NULL) {
	  inventario = obtener_Inventario(pch);
	  if(inventario != NULL) {
	    strcat(aux, inventario->producto);
	    strcat(aux, "&");
	    sprintf(convert, "%d", inventario->cantidad);
	    strcat(aux, convert);
	    strcat(aux, "&");
	    sprintf(convert, "%f", inventario->precio);
	    strcat(aux, convert);
	    strcat(aux,"&");
	  }								 	
	  pch = strtok (NULL, "&");
	}
	
	result = aux;
	return &result;
}

/**
 * Dado un string con todos los productos y cantidad a solicitar, el servidor 
 * reescribe el archivo inventario con las modificaciones respectivas.
 * @param **argp variable que contiene los pedidos solicitados junto con al cantidad pedida
 * pasada por el cliente a este servidor.
 * @return devuelve 1 si la operacion fue realizada exitosamente. En caso contrario devuelve
 * 0.
 */
int * realizar_pedido_productos_1_svc(char **argp, struct svc_req *rqstp) {
	static int  result;
	int i;
	int sizeInventarios;
	Inventario * inventario;
	
	FILE *fp;

	if((fp = fopen(INVENTARIO,"w")) == NULL) {
	  printf("Error");
	  exit(1);
	}
	
	//printf("nombre del archivo %s\n", archivoInventario);
	actualizarInventario(*argp);
	printf("\n\nEl inventario luego de actualizar es: \n");
	imprimirInventarios((Inventario **)begin(inventarios), size(inventarios));
	
	sizeInventarios = size(inventarios);
	for(i = 0; i < sizeInventarios; ++i) {
	  inventario = (Inventario *)at(inventarios, i);
	  fprintf(fp,"%s & %d & %f\n", inventario->producto, inventario->cantidad, inventario->precio);
	}
	fclose(fp);
	
	result = 1;
	return &result;
}
