/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LACADENA_H_RPCGEN
#define _LACADENA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define LA_CADENA 0x30000001
#define LA_CADENA_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define obtenerInventario 1
extern  char ** obtenerinventario_1(char **, CLIENT *);
extern  char ** obtenerinventario_1_svc(char **, struct svc_req *);
#define realizar_Pedido_Productos 2
extern  int * realizar_pedido_productos_1(char **, CLIENT *);
extern  int * realizar_pedido_productos_1_svc(char **, struct svc_req *);
extern int la_cadena_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define obtenerInventario 1
extern  char ** obtenerinventario_1();
extern  char ** obtenerinventario_1_svc();
#define realizar_Pedido_Productos 2
extern  int * realizar_pedido_productos_1();
extern  int * realizar_pedido_productos_1_svc();
extern int la_cadena_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LACADENA_H_RPCGEN */
